services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: bravado-api
    stdin_open: true
    tty: true
    environment:
      - BINDING=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - CACHE_DATABASE_URL=postgres://postgres:postgres@postgres:5432
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - postgres

  postgres:
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  postgres:
